secrets:
  discord_token: ""
  wolfram_alpha_appid: ""
  open_weather_appid: ""
  bing:
    clientid: ""
    secret: ""
  osu_api_key: ""

  db:
    dbname: "lemon"
    username: "lemon"
    password: "lemon"
