- name: Install postgres
  apt:
    name: "{{ item }}"
  with_items:
    - postgresql

- name: Create database
  postgresql_db:
    name: "{{ secrets.db.dbname }}"

- name: Create database user
  postgresql_user:
    db: "{{ secrets.db.dbname }}"
    name: "{{ secrets.db.username }}"
    password: "{{ secrets.db.password }}"
    priv: "ALL"
