- name: Configure server
  hosts: server
  remote_user: root
  become: yes
  gather_facts: no

  vars:
    app_name: lemon

  pre_tasks:
    - name: Install python on remote machine
      raw: test -e /usr/bin/python || (apt -y update && apt install -y python-minimal)
      changed_when: False

  tasks:
    - include: deployment_dependencies.yml

    - name: Create group
      group:
        name: "{{ app_name }}"

    - name: Create user
      user:
        name: "{{ app_name }}"

    - include: postgres.yml

    - name: Install required packages
      apt:
        name: "{{ item }}"
      with_items:
        - python3
        - python3-pip
        - libpq-dev

    - name: Install pip dependencies
      pip:
        name: "{{ item }}"
        executable: pip3
      with_items:
        - discord.py
        - cleverbot
        - requests
        - BingTranslator
        - bs4
        - wolframalpha
        - lxml
        - psycopg2

    - name: Copy source to server
      synchronize:
        src: ../src
        dest: "/home/{{ app_name }}"
        delete: yes
      notify:
        - restart service

    - name: Create service
      template:
        src: templates/systemd.service.j2
        dest: "/etc/systemd/system/{{ app_name }}.service"
      notify:
        - reload service
        - restart service

    - name: enable and start service
      service:
        name: "{{ app_name }}"
        state: started

  handlers:
    - name: reload service
      shell: systemctl daemon-reload

    - name: restart service
      service:
        name: "{{ app_name }}"
        state: restarted
