- name: Configure server
  hosts: server
  remote_user: root
  become: yes
  gather_facts: no

  vars:
    app_name: lemon

  pre_tasks:
    - name: Install python on remote machine
      raw: test -e /usr/bin/python || (apt -y update && apt install -y python-minimal)
      changed_when: False

  tasks:
    - name: Create group
      group:
        name: "{{ app_name }}"

    - name: Create user
      user:
        name: "{{ app_name }}"

    - name: Copy source to server
      synchronize:
        src: ../src
        dest: "/home/{{ app_name }}"
        delete: yes

    - name: Install required packages
      apt:
        name: "{{ item }}"
      with_items:
        - python3
        - python3-pip

    - name: Install pip dependencies
      pip:
        name: "{{ item }}"
        executable: pip3
      with_items:
        - discord.py
        - cleverbot
        - requests
        - BingTranslator
        - bs4
        - wolframalpha
        - lxml

    - name: Create service
      template:
        src: templates/systemd.service.j2
        dest: "/etc/systemd/system/{{ app_name }}.service"
      register: unit_file

    - name: Reload units
      shell: systemctl daemon-reload
      when: unit_file.changed

    - name: Restart app
      service:
        name: "{{ app_name }}"
        state: restarted
